// export const countries = [
//   "Andorra",
//   "United Arab Emirates",
//   "Afghanistan",
//   "Antigua and Barbuda",
//   "Anguilla",
//   "Albania",
//   "Armenia",
//   "Angola",
//   "Antarctica",
//   "Argentina",
//   "American Samoa",
//   "Austria",
//   "Australia",
//   "Aruba",
//   "Alland Islands",
//   "Azerbaijan",
//   "Bosnia and Herzegovina",
//   "Barbados",
//   "Bangladesh",
//   "Belgium",
//   "Burkina Faso",
//   "Bulgaria",
//   "Bahrain",
//   "Burundi",
//   "Benin",
//   "Saint Barthelemy",
//   "Bermuda",
//   "Brunei Darussalam",
//   "Bolivia",
//   "Brazil",
//   "Bahamas",
//   "Bhutan",
//   "Bouvet Island",
//   "Botswana",
//   "Belarus",
//   "Belize",
//   "Canada",
//   "Cocos (Keeling) Islands",
//   "Congo, Democratic Republic of the",
//   "Central African Republic",
//   "Congo, Republic of the",
//   "Switzerland",
//   "Cote d'Ivoire",
//   "Cook Islands",
//   "Chile",
//   "Cameroon",
//   "China",
//   "Colombia",
//   "Costa Rica",
//   "Cuba",
//   "Cape Verde",
//   "Curacao",
//   "Christmas Island",
//   "Cyprus",
//   "Czech Republic",
//   "Germany",
//   "Djibouti",
//   "Denmark",
//   "Dominica",
//   "Dominican Republic",
//   "Algeria",
//   "Ecuador",
//   "Estonia",
//   "Egypt",
//   "Western Sahara",
//   "Eritrea",
//   "Spain",
//   "Ethiopia",
//   "Finland",
//   "Fiji",
//   "Falkland Islands (Malvinas)",
//   "Micronesia, Federated States of",
//   "Faroe Islands",
//   "France",
//   "Gabon",
//   "United Kingdom",
//   "Grenada",
//   "Georgia",
//   "French Guiana",
//   "Guernsey",
//   "Ghana",
//   "Gibraltar",
//   "Greenland",
//   "Gambia",
//   "Guinea",
//   "Guadeloupe",
//   "Equatorial Guinea",
//   "Greece",
//   "South Georgia and the South Sandwich Islands",
//   "Guatemala",
//   "Guam",
//   "Guinea-Bissau",
//   "Guyana",
//   "Hong Kong",
//   "Heard Island and McDonald Islands",
//   "Honduras",
//   "Croatia",
//   "Haiti",
//   "Hungary",
//   "Indonesia",
//   "Ireland",
//   "Israel",
//   "Isle of Man",
//   "India",
//   "British Indian Ocean Territory",
//   "Iraq",
//   "Iran, Islamic Republic of",
//   "Iceland",
//   "Italy",
//   "Jersey",
//   "Jamaica",
//   "Jordan",
//   "Japan",
//   "Kenya",
//   "Kyrgyzstan",
//   "Cambodia",
//   "Kiribati",
//   "Comoros",
//   "Saint Kitts and Nevis",
//   "Korea, Democratic People's Republic of",
//   "Korea, Republic of",
//   "Kuwait",
//   "Cayman Islands",
//   "Kazakhstan",
//   "Lao People's Democratic Republic",
//   "Lebanon",
//   "Saint Lucia",
//   "Liechtenstein",
//   "Sri Lanka",
//   "Liberia",
//   "Lesotho",
//   "Lithuania",
//   "Luxembourg",
//   "Latvia",
//   "Libya",
//   "Morocco",
//   "Monaco",
//   "Moldova, Republic of",
//   "Montenegro",
//   "Saint Martin (French part)",
//   "Madagascar",
//   "Marshall Islands",
//   "Macedonia, the Former Yugoslav Republic of",
//   "Mali",
//   "Myanmar",
//   "Mongolia",
//   "Macao",
//   "Northern Mariana Islands",
//   "Martinique",
//   "Mauritania",
// ];

// const translatedCountries = [
//   "أندورا",
//   "الإمارات العربية المتحدة",
//   "أفغانستان",
//   "أنتيغوا وبربودا",
//   "أنغويلا",
//   "ألبانيا",
//   "أرمينيا",
//   "أنغولا",
//   "القارة المتجمدة الجنوبية",
//   "الأرجنتين",
//   "ساموا الأمريكية",
//   "النمسا",
//   "أستراليا",
//   "أروبا",
//   "جزر آلاند",
//   "أذربيجان",
//   "البوسنة والهرسك",
//   "بربادوس",
//   "بنجلاديش",
//   "بلجيكا",
//   "بوركينا فاسو",
//   "بلغاريا",
//   "البحرين",
//   "بوروندي",
//   "بنين",
//   "سان بارتيليمي",
//   "برمودا",
//   "بروناي",
//   "بوليفيا",
//   "البرازيل",
//   "الباهاماس",
//   "بوتان",
//   "جزيرة بوفيه",
//   "بوتسوانا",
//   "بيلاروسيا",
//   "بليز",
//   "كندا",
//   "جزر كوكوس (كيلينغ)",
//   "جمهورية الكونغو الديمقراطية",
//   "جمهورية أفريقيا الوسطى",
//   "جمهورية الكونغو",
//   "سويسرا",
//   "ساحل العاج",
//   "جزر كوك",
//   "تشيلي",
//   "الكاميرون",
//   "الصين",
//   "كولومبيا",
//   "كوستاريكا",
//   "كوبا",
//   "الرأس الأخضر",
//   "كوراساو",
//   "جزيرة عيد الميلاد",
//   "قبرص",
//   "جمهورية التشيك",
//   "ألمانيا",
//   "جيبوتي",
//   "الدانمرك",
//   "دومينيكا",
//   "جمهورية الدومينيكان",
//   "الجزائر",
//   "الإكوادور",
//   "استونيا",
//   "مصر",
//   "الصحراء الغربية",
//   "إريتريا",
//   "إسبانيا",
//   "إثيوبيا",
//   "فنلندا",
//   "فيجي",
//   "جزر فوكلاند (مالفيناس)",
//   "ميكرونيزيا، الدول الموحدة",
//   "جزر فارو",
//   "فرنسا",
//   "الغابون",
//   "المملكة المتحدة",
//   "غرينادا",
//   "جورجيا",
//   "غويانا الفرنسية",
//   "غيرنزي",
//   "غانا",
//   "جبل طارق",
//   "جرينلاند",
//   "غامبيا",
//   "غينيا",
//   "غوادلوب",
//   "غينيا الاستوائية",
//   "اليونان",
//   "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
//   "غواتيمالا",
//   "غوام",
//   "غينيا بيساو",
//   "غيانا",
//   "هونغ كونغ",
//   "جزيرة هيرد وجزر ماكدونالد",
//   "هندوراس",
//   "كرواتيا",
//   "هايتي",
//   "هنغاريا",
//   "إندونيسيا",
//   "أيرلندا",
//   "إسرائيل",
//   "جزيرة مان",
//   "الهند",
//   "إقليم المحيط الهندي البريطاني",
//   "العراق",
//   "جمهورية إيران الإسلامية",
//   "آيسلندا",
//   "إيطاليا",
//   "جيرسي",
//   "جامايكا",
//   "الأردن",
//   "اليابان",
//   "كينيا",
//   "قرغيزستان",
//   "كمبوديا",
//   "كيريباتي",
//   "جزر القمر",
//   "سانت كيتس ونيفيس",
//   "جمهورية كوريا الشعبية الديمقراطية",
//   "جمهورية كوريا",
//   "الكويت",
//   "جزر كايمان",
//   "كازاخستان",
//   "جمهورية لاو الديمقراطية الشعبية",
//   "لبنان",
//   "سانت لوسيا",
//   "ليختنشتاين",
//   "سريلانكا",
//   "ليبيريا",
//   "ليسوتو",
//   "ليتوانيا",
//   "لوكسمبورج",
//   "لاتفيا",
//   "ليبيا",
//   "المغرب",
//   "موناكو",
//   "جمهورية مولدوفا",
//   "الجبل الأسود",
//   "سان مارتين (الجزء الفرنسي)",
//   "مدغشقر",
//   "جزر مارشال",
//   "مقدونيا، جمهورية يوغوسلافيا السابقة",
//   "مالي",
//   "ميانمار",
//   "منغوليا",
//   "ماكاو",
//   "جزر ماريانا الشمالية",
//   "مارتينيك",
//   "موريتانيا",
// ];

export const countries = [
  "Andorra (أندورا)",
  "United Arab Emirates (الإمارات العربية المتحدة)",
  "Afghanistan (أفغانستان)",
  "Antigua and Barbuda (أنتيغوا وبربودا)",
  "Anguilla (أنغويلا)",
  "Albania (ألبانيا)",
  "Armenia (أرمينيا)",
  "Angola (أنغولا)",
  "Antarctica (القارة المتجمدة الجنوبية)",
  "Argentina (الأرجنتين)",
  "American Samoa (ساموا الأمريكية)",
  "Austria (النمسا)",
  "Australia (أستراليا)",
  "Aruba (أروبا)",
  "Alland Islands (جزر آلاند)",
  "Azerbaijan (أذربيجان)",
  "Bosnia and Herzegovina (البوسنة والهرسك)",
  "Barbados (بربادوس)",
  "Bangladesh (بنجلاديش)",
  "Belgium (بلجيكا)",
  "Burkina Faso (بوركينا فاسو)",
  "Bulgaria (بلغاريا)",
  "Bahrain (البحرين)",
  "Burundi (بوروندي)",
  "Benin (بنين)",
  "Saint Barthelemy (سان بارتيليمي)",
  "Bermuda (برمودا)",
  "Brunei Darussalam (بروناي دار السلام)",
  "Bolivia (بوليفيا)",
  "Brazil (البرازيل)",
  "Bahamas (الباهاما)",
  "Bhutan (بوتان)",
  "Bouvet Island (جزيرة بوفيه)",
  "Botswana (بوتسوانا)",
  "Belarus (بيلاروسيا)",
  "Belize (بيليز)",
  "Canada (كندا)",
  "Cocos (Keeling) Islands (جزر كوكوس (كيلينغ))",
  "Congo, Democratic Republic of the (جمهورية الكونغو الديمقراطية)",
  "Central African Republic (جمهورية أفريقيا الوسطى)",
  "Congo, Republic of the (جمهورية الكونغو)",
  "Switzerland (سويسرا)",
  "Cote d'Ivoire (ساحل العاج)",
  "Cook Islands (جزر كوك)",
  "Chile (تشيلي)",
  "Cameroon (الكاميرون)",
  "China (الصين)",
  "Colombia (كولومبيا)",
  "Costa Rica (كوستاريكا)",
  "Cuba (كوبا)",
  "Cape Verde (الرأس الأخضر)",
  "Curacao (كوراساو)",
  "Christmas Island (جزيرة عيد الميلاد)",
  "Cyprus (قبرص)",
  "Czech Republic (جمهورية التشيك)",
  "Germany (ألمانيا)",
  "Djibouti (جيبوتي)",
  "Denmark (الدانمرك)",
  "Dominica (دومينيكا)",
  "Dominican Republic (جمهورية الدومينيكان)",
  "Algeria (الجزائر)",
  "Ecuador (الإكوادور)",
  "Estonia (استونيا)",
  "Egypt (مصر)",
  "Western Sahara (الصحراء الغربية)",
  "Eritrea (إريتريا)",
  "Spain (إسبانيا)",
  "Ethiopia (إثيوبيا)",
  "Finland (فنلندا)",
  "Fiji (فيجي)",
  "Falkland Islands (Malvinas) (جزر فوكلاند (مالفيناس))",
  "Micronesia, Federated States of (ميكرونيزيا، الدول الموحدة)",
  "Faroe Islands (جزر فارو)",
  "France (فرنسا)",
  "Gabon (الغابون)",
  "United Kingdom (المملكة المتحدة)",
  "Grenada (غرينادا)",
  "Georgia (جورجيا)",
  "French Guiana (غويانا الفرنسية)",
  "Guernsey (غيرنزي)",
  "Ghana (غانا)",
  "Gibraltar (جبل طارق)",
  "Greenland (جرينلاند)",
  "Gambia (غامبيا)",
  "Guinea (غينيا)",
  "Guadeloupe (غوادلوب)",
  "Equatorial Guinea (غينيا الاستوائية)",
  "Greece (اليونان)",
  "South Georgia and the South Sandwich Islands (جورجيا الجنوبية وجزر ساندويتش الجنوبية)",
  "Guatemala (غواتيمالا)",
  "Guam (غوام)",
  "Guinea-Bissau (غينيا بيساو)",
  "Guyana (غيانا)",
  "Hong Kong (هونغ كونغ)",
  "Heard Island and McDonald Islands (جزيرة هيرد وجزر ماكدونالد)",
  "Honduras (هندوراس)",
  "Croatia (كرواتيا)",
  "Haiti (هايتي)",
  "Hungary (هنغاريا)",
  "Indonesia (إندونيسيا)",
  "Ireland (أيرلندا)",
  "Israel (إسرائيل)",
  "Isle of Man (جزيرة مان)",
  "India (الهند)",
  "British Indian Ocean",
  "Palestine (فلسطين)",
];
