import * as yup from "yup";

export const schema = yup.object().shape({
  role: yup.string().required("required"),
  TalentSeeker: yup.string().required("required"),
  firstName: yup.string().required("required"),
  lastName: yup.string().required("required"),
  talentTypes: yup.array().required("required"),
  talent: yup.string().required("required"),
  talentType: yup.string().required("required"),
  email: yup.string().email("Invalid email").required("required"),
  gender: yup.string().required("required"),
  country: yup.string().required("required"),
  phoneNumber: yup.number().required("required"),
  password: yup.string().required("required"),
  companyName: yup.string().required("required"),
  city: yup.string().required("required"),
  citizenship: yup.string().required("required"),
  title: yup.string().required("this field is required"),
  company: yup.string().required("this field is required"),
  productionDescription: yup.string().required("this field is required"),
  productionPersonnel: yup.array().required("this field is required"),
  name: yup.string().required("this field is required"),
  type: yup.string().required("this field is required"),
  Skills: yup.array().required("this field is required"),
  description: yup.string().required("this field is required"),
  location: yup.string().required("this field is required"),
  isPaid: yup.boolean().required("this field is required"),
  paidType: yup.string().required("this field is required"),
  paidRate: yup.string().required("this field is required"),
  dop: yup.string().required("required"),
  otherTalentType: yup.string().required("required"),
  otherRoleType: yup.string().required("required"),
  expirationDate: yup.string().required("required"),
});
