import * as yup from "yup";

export const schema = yup.object().shape({
  Talent: yup.string().required("required"),
  TalentSeeker: yup.string().required("required"),
  FirstName: yup.string().required("required"),
  LastName: yup.string().required("required"),
  TalentType: yup.string().required("required"),
  talent: yup.string().required("required"),
  email: yup.string().email("Invalid email").required("required"),
  Gender: yup.string().required("required"),
  Country: yup.string().required("required"),
  PhoneNumber: yup.number().required("required"),
  Password: yup.string().required("required"),
  CompanyName: yup.string().required("required"),
  City: yup.string().required("required"),
  TitleOfProduction: yup.string().required("this field is required"),
  ProductionCompany: yup.string().required("this field is required"),
  ProductionDescription: yup.string().required("this field is required"),
  RoleName: yup.string().required("this field is required"),
  SubType: yup.string().required("this field is required"),
  Skills: yup.array().required("this field is required"),
  RoleDescription: yup.string().required("this field is required"),
  FilmingCity: yup.string().required("this field is required"),
  compensationAgreement: yup.string().required("this field is required"),
  period: yup.string().required("this field is required"),
  Rate: yup.string().required("this field is required"),
});
