import * as yup from "yup";

export const schema = yup.object().shape({
  role: yup.string().required("required"),
  TalentSeeker: yup.string().required("required"),
  firstName: yup.string().required("required"),
  lastName: yup.string().required("required"),
  talentTypes: yup.array().required("required"),
  talent: yup.string().required("required"),
  email: yup.string().email("Invalid email").required("required"),
  gender: yup.string().required("required"),
  country: yup.string().required("required"),
  phoneNumber: yup.number().required("required"),
  password: yup.string().required("required"),
  companyName: yup.string().required("required"),
  city: yup.string().required("required"),
  title: yup.string().required("this field is required"),
  company: yup.string().required("this field is required"),
  productionDescription: yup.string().required("this field is required"),
  productionPersonnel: yup.array().required("this field is required"),
  RoleName: yup.string().required("this field is required"),
  SubType: yup.string().required("this field is required"),
  Skills: yup.array().required("this field is required"),
  RoleDescription: yup.string().required("this field is required"),
  FilmingCity: yup.string().required("this field is required"),
  compensationAgreement: yup.string().required("this field is required"),
  period: yup.string().required("this field is required"),
  Rate: yup.string().required("this field is required"),
  dop: yup.string().required("required"),
});
