// export const SKILLS = [
//   "Accordion",
//   "Teamwork",
//   "Problem Solving",
//   "Critical Thinking",
//   "Leadership",
//   "Time Management",
//   "Adaptability",
//   "Creativity",
//   "Decision Making",
//   "Negotiation",
//   "Conflict Resolution",
//   "Organizational",
//   "Technical Proficiency",
//   "Analytical Skills",
//   "Attention to Detail",
//   "Project Management",
//   "Research",
//   "Networking",
//   "Presentation",
//   "Customer Service",
//   "Sales",
//   "Coding",
//   "Data Analysis",
//   "Digital Marketing",
//   "Graphic Design",
//   "Video Editing",
//   "Foreign Language",
//   "Public Speaking",
//   "Writing",
//   "Financial Analysis",
//   "Problem Diagnosis",
//   "Mechanical Skills",
//   "Electrical Skills",
//   "Carpentry",
//   "Plumbing",
//   "Data Entry",
//   "Mathematical Skills",
//   "Medical Knowledge",
//   "Legal Knowledge",
//   "Quality Control",
//   "Lab Techniques",
//   "Cooking",
//   "Photography",
//   "Social Media Management",
//   "Content Creation",
//   "Animation",
// ];

export const SKILLS = [
  "Accordion",
  "Acoustic Bass",
  "Aerobics",
  "African",
  "Afrikaans",
  "Algerian accent",
  "American - Boston",
  "American - Cajun",
  "American - Creole",
  "American - Minnesota",
  "American - New England",
  "American - New York",
  "American - Philadelphia",
  "American - Southern",
  "American - Standard/General",
  "American - Texan",
  "Arabic",
  "Archery",
  "Armenian",
  "Asian",
  "Asian - Chinese",
  "Asian - Japanese",
  "Asian - Korean",
  "Auctioneer",
  "Audio Prompter",
  "Australian",
  "Autoharp",
  "Badminton",
  "Bagpipes",
  "Banjo",
  "Bartender - Vegas Style Flair",
  "Baseball",
  "Basketball",
  "Bassoon",
  "Baton Twirling",
  "Bengali",
  "Billiards/Pool Player",
  "Boating - engine",
  "Boating - Sail",
  "Body Building",
  "Body Surfing",
  "Bones",
  "Bongos",
  "Bowling",
  "Boxing",
  "Brass Instruments",
  "British - BBC English",
  "British - Birmingham",
  "British - Cockney",
  "British - Geordie",
  "British - Scouse/Liverpool",
  "British - Yorkshire",
  "Bulgarian",
  "Canadian",
  "Canoeing",
  "Cantonese",
  "Cello",
  "Chef",
  "Chef - Garde Manger",
];
