export const SKILLS = [
  "Accordion",
  "Teamwork",
  "Problem Solving",
  "Critical Thinking",
  "Leadership",
  "Time Management",
  "Adaptability",
  "Creativity",
  "Decision Making",
  "Negotiation",
  "Conflict Resolution",
  "Organizational",
  "Technical Proficiency",
  "Analytical Skills",
  "Attention to Detail",
  "Project Management",
  "Research",
  "Networking",
  "Presentation",
  "Customer Service",
  "Sales",
  "Coding",
  "Data Analysis",
  "Digital Marketing",
  "Graphic Design",
  "Video Editing",
  "Foreign Language",
  "Public Speaking",
  "Writing",
  "Financial Analysis",
  "Problem Diagnosis",
  "Mechanical Skills",
  "Electrical Skills",
  "Carpentry",
  "Plumbing",
  "Data Entry",
  "Mathematical Skills",
  "Medical Knowledge",
  "Legal Knowledge",
  "Quality Control",
  "Lab Techniques",
  "Cooking",
  "Photography",
  "Social Media Management",
  "Content Creation",
  "Animation",
];
